server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:./logistics.h2;AUTO_SERVER=true
  jpa:
    hibernate:
      ddl-auto: create-drop
rsa:
  private-key: classpath:certificates/private.pem
  public-key: classpath:certificates/public.pem

datasets:
  users:
    - username: user
      password: password
      email: user@me.com
    - username: admin
      password: secret
      email: admin@me.com
  papers:
    - name: A Treaty On Nothing
    - name: A Guide To Nihilism
    - name: A Review of Futility


